/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "AMFStatusChangeSubscribeModifyApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

AMFStatusChangeSubscribeModifyApi::AMFStatusChangeSubscribeModifyApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void AMFStatusChangeSubscribeModifyApi::init() {
    setupRoutes();
}

void AMFStatusChangeSubscribeModifyApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Put(*router, base + "/subscriptions/:subscriptionId", Routes::bind(&AMFStatusChangeSubscribeModifyApi::a_mf_status_change_subscribe_modfy_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&AMFStatusChangeSubscribeModifyApi::amf_status_change_subscribe_modify_api_default_handler, this));
}

void AMFStatusChangeSubscribeModifyApi::a_mf_status_change_subscribe_modfy_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto subscriptionId = request.param(":subscriptionId").as<std::string>();
    
    // Getting the body param
    
    SubscriptionData subscriptionData;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      subscriptionData.fromJson(request_body);
    
      this->a_mf_status_change_subscribe_modfy(subscriptionId, subscriptionData, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void AMFStatusChangeSubscribeModifyApi::amf_status_change_subscribe_modify_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

