/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "AMFStatusChangeUnSubscribeApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

AMFStatusChangeUnSubscribeApi::AMFStatusChangeUnSubscribeApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void AMFStatusChangeUnSubscribeApi::init() {
    setupRoutes();
}

void AMFStatusChangeUnSubscribeApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Delete(*router, base + "/subscriptions/:subscriptionId", Routes::bind(&AMFStatusChangeUnSubscribeApi::a_mf_status_change_un_subscribe_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&AMFStatusChangeUnSubscribeApi::amf_status_change_un_subscribe_api_default_handler, this));
}

void AMFStatusChangeUnSubscribeApi::a_mf_status_change_un_subscribe_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto subscriptionId = request.param(":subscriptionId").as<std::string>();
    
    try {
      this->a_mf_status_change_un_subscribe(subscriptionId, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void AMFStatusChangeUnSubscribeApi::amf_status_change_un_subscribe_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

