/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AMFStatusChangeSubscribeModifyApi.h
 *
 * 
 */

#ifndef AMFStatusChangeSubscribeModifyApi_H_
#define AMFStatusChangeSubscribeModifyApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "ProblemDetails.h"
#include "SubscriptionData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  AMFStatusChangeSubscribeModifyApi {
public:
    AMFStatusChangeSubscribeModifyApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~AMFStatusChangeSubscribeModifyApi() {}
    void init();

    const std::string base = "/namf-comm/v1";

private:
    void setupRoutes();

    void a_mf_status_change_subscribe_modfy_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void amf_status_change_subscribe_modify_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Namf_Communication AMF Status Change Subscribe Modify service Operation
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="subscriptionId">AMF Status Change Subscription Identifier</param>
    /// <param name="subscriptionData"></param>
    virtual void a_mf_status_change_subscribe_modfy(const std::string &subscriptionId, const SubscriptionData &subscriptionData, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* AMFStatusChangeSubscribeModifyApi_H_ */

