/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N1N2MessageTransferApi.h
 *
 * 
 */

#ifndef N1N2MessageTransferApi_H_
#define N1N2MessageTransferApi_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>


#include "N1N2MessageData.h"
#include "N1N2MessageTransferError.h"
#include "N1N2MessageTransferRspData.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  N1N2MessageTransferApi {
public:
    N1N2MessageTransferApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~N1N2MessageTransferApi() {}
    void init();

    const std::string base = "/namf-comm/v1";

private:
    void setupRoutes();

    void n1_n2_message_transfer_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void n1_n2_message_transfer_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Rest::Router> router;

    /// <summary>
    /// Namf_Communication N1N2 Message Transfer (UE Specific) service Operation
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="ueContextId">UE Context Identifier</param>
    /// <param name="n1N2MessageData"></param>
    virtual void n1_n2_message_transfer(const std::string &ueContextId, const N1N2MessageData &n1N2MessageData, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* N1N2MessageTransferApi_H_ */

