/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "N1N2MessageUnSubscribeApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;


N1N2MessageUnSubscribeApi::N1N2MessageUnSubscribeApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void N1N2MessageUnSubscribeApi::init() {
    setupRoutes();
}

void N1N2MessageUnSubscribeApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Delete(*router, base + "/ue-contexts/:ueContextId/n1-n2-messages/subscriptions/:subscriptionId", Routes::bind(&N1N2MessageUnSubscribeApi::n1_n2_message_un_subscribe_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&N1N2MessageUnSubscribeApi::n1_n2_message_un_subscribe_api_default_handler, this));
}

void N1N2MessageUnSubscribeApi::n1_n2_message_un_subscribe_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto subscriptionId = request.param(":subscriptionId").as<std::string>();
    
    try {
      this->n1_n2_message_un_subscribe(subscriptionId, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void N1N2MessageUnSubscribeApi::n1_n2_message_un_subscribe_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

