/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "N1N2MessageSubscribeApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

N1N2MessageSubscribeApi::N1N2MessageSubscribeApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void N1N2MessageSubscribeApi::init() {
    setupRoutes();
}

void N1N2MessageSubscribeApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/ue-contexts/:ueContextId/n1-n2-messages/subscriptions", Routes::bind(&N1N2MessageSubscribeApi::n1_n2_message_subscribe_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&N1N2MessageSubscribeApi::n1_n2_message_subscribe_api_default_handler, this));
}

void N1N2MessageSubscribeApi::n1_n2_message_subscribe_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto ueContextId = request.param(":ueContextId").as<std::string>();
    
    // Getting the body param
    
    UeN1N2InfoSubscriptionCreateData ueN1N2InfoSubscriptionCreateData;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      ueN1N2InfoSubscriptionCreateData.fromJson(request_body);
    
      this->n1_n2_message_subscribe(ueContextId, ueN1N2InfoSubscriptionCreateData, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void N1N2MessageSubscribeApi::n1_n2_message_subscribe_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

