/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "NonUEN2MessageTransferApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

NonUEN2MessageTransferApi::NonUEN2MessageTransferApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void NonUEN2MessageTransferApi::init() {
    setupRoutes();
}

void NonUEN2MessageTransferApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/non-ue-n2-messages/transfer", Routes::bind(&NonUEN2MessageTransferApi::non_ue_n2_message_transfer_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&NonUEN2MessageTransferApi::non_uen2_message_transfer_api_default_handler, this));
}

void NonUEN2MessageTransferApi::non_ue_n2_message_transfer_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the body param
    
    N2InformationTransferReqData n2InformationTransferReqData;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      n2InformationTransferReqData.fromJson(request_body);
    
      this->non_ue_n2_message_transfer(n2InformationTransferReqData, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void NonUEN2MessageTransferApi::non_uen2_message_transfer_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

