/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "NonUEN2InfoSubscribeApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

NonUEN2InfoSubscribeApi::NonUEN2InfoSubscribeApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void NonUEN2InfoSubscribeApi::init() {
    setupRoutes();
}

void NonUEN2InfoSubscribeApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(*router, base + "/non-ue-n2-messages/subscriptions", Routes::bind(&NonUEN2InfoSubscribeApi::non_ue_n2_info_subscribe_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&NonUEN2InfoSubscribeApi::non_uen2_info_subscribe_api_default_handler, this));
}

void NonUEN2InfoSubscribeApi::non_ue_n2_info_subscribe_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the body param
    
    NonUeN2InfoSubscriptionCreateData nonUeN2InfoSubscriptionCreateData;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
    
      nonUeN2InfoSubscriptionCreateData.fromJson(request_body);
    
      this->non_ue_n2_info_subscribe(nonUeN2InfoSubscriptionCreateData, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void NonUEN2InfoSubscribeApi::non_uen2_info_subscribe_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

