/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfCreateEventSubscription.h
 *
 * 
 */

#ifndef AmfCreateEventSubscription_H_
#define AmfCreateEventSubscription_H_


#include "ModelBase.h"

#include <string>
#include "AmfEventSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AmfCreateEventSubscription
    : public ModelBase
{
public:
    AmfCreateEventSubscription();
    virtual ~AmfCreateEventSubscription();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AmfCreateEventSubscription members

    /// <summary>
    /// 
    /// </summary>
    AmfEventSubscription getSubscription() const;
    void setSubscription(AmfEventSubscription const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

protected:
    AmfEventSubscription m_Subscription;

    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}
}
}
}

#endif /* AmfCreateEventSubscription_H_ */
