/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfCreatedEventSubscription.h
 *
 * 
 */

#ifndef AmfCreatedEventSubscription_H_
#define AmfCreatedEventSubscription_H_


#include "ModelBase.h"

#include "AmfEventReport.h"
#include <string>
#include "AmfEventSubscription.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AmfCreatedEventSubscription
    : public ModelBase
{
public:
    AmfCreatedEventSubscription();
    virtual ~AmfCreatedEventSubscription();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AmfCreatedEventSubscription members

    /// <summary>
    /// 
    /// </summary>
    AmfEventSubscription getSubscription() const;
    void setSubscription(AmfEventSubscription const& value);
        /// <summary>
    /// 
    /// </summary>
    AmfEventReport getReports() const;
    void setReports(AmfEventReport const& value);
    bool reportsIsSet() const;
    void unsetReports();
    /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

protected:
    AmfEventSubscription m_Subscription;

    AmfEventReport m_Reports;
    bool m_ReportsIsSet;
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}
}
}
}

#endif /* AmfCreatedEventSubscription_H_ */
