/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfEventNotification.h
 *
 * 
 */

#ifndef AmfEventNotification_H_
#define AmfEventNotification_H_


#include "ModelBase.h"

#include "AmfEventReport.h"
#include <string>
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AmfEventNotification
    : public ModelBase
{
public:
    AmfEventNotification();
    virtual ~AmfEventNotification();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AmfEventNotification members

    /// <summary>
    /// 
    /// </summary>
    std::string getSubscriptionId() const;
    void setSubscriptionId(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getNotifCorelationId() const;
    void setNotifCorelationId(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<AmfEventReport>& getReports();
    bool reportsIsSet() const;
    void unsetReports();

protected:
    std::string m_SubscriptionId;

    std::string m_NotifCorelationId;

    std::vector<AmfEventReport> m_Reports;
    bool m_ReportsIsSet;
};

}
}
}
}

#endif /* AmfEventNotification_H_ */
