/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfStatusChangeNotification.h
 *
 * 
 */

#ifndef AmfStatusChangeNotification_H_
#define AmfStatusChangeNotification_H_


#include "ModelBase.h"

#include "AmfStatusInfo.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AmfStatusChangeNotification
    : public ModelBase
{
public:
    AmfStatusChangeNotification();
    virtual ~AmfStatusChangeNotification();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AmfStatusChangeNotification members

    /// <summary>
    /// 
    /// </summary>
    AmfStatusInfo getAmfStatusInfo() const;
    void setAmfStatusInfo(AmfStatusInfo const& value);
    
protected:
    AmfStatusInfo m_AmfStatusInfo;

};

}
}
}
}

#endif /* AmfStatusChangeNotification_H_ */
