/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AreaOfValidity.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

AreaOfValidity::AreaOfValidity()
{
    
}

AreaOfValidity::~AreaOfValidity()
{
}

void AreaOfValidity::validate()
{
    // TODO: implement validation
}

nlohmann::json AreaOfValidity::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["taList"] = ModelBase::toJson(m_TaList);
    

    return val;
}

void AreaOfValidity::fromJson(const nlohmann::json& val)
{
    
}


Tai AreaOfValidity::getTaList() const
{
    return m_TaList;
}
void AreaOfValidity::setTaList(Tai const& value)
{
    m_TaList = value;
    
}

}
}
}
}

