/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AssignEbi.h
 *
 * 
 */

#ifndef AssignEbi_H_
#define AssignEbi_H_


#include "ModelBase.h"
#include "EpsBearerId.h"

#include <vector>
#include "Arp.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AssignEbi
    : public ModelBase
{
public:
    AssignEbi();
    virtual ~AssignEbi();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AssignEbi members

    /// <summary>
    /// 
    /// </summary>
    int32_t getPduSessionId() const;
    void setPduSessionId(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<Arp>& getArps();
    bool arpsIsSet() const;
    void unsetArps();
    /// <summary>
    /// 
    /// </summary>
    std::vector<EpsBearerId>& getReleasedEbiList();
    bool releasedEbiListIsSet() const;
    void unsetReleasedEbiList();
protected:
    int32_t m_PduSessionId;

    std::vector<Arp> m_Arps;
    bool m_ArpsIsSet;
    std::vector<EpsBearerId> m_ReleasedEbiList;
    bool m_ReleasedEbiListIsSet;
};

}
}
}
}

#endif /* AssignEbi_H_ */
