/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CipheringAlgorithm.h
 *
 * 
 */

#ifndef CipheringAlgorithm_H_
#define CipheringAlgorithm_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  CipheringAlgorithm
    : public ModelBase
{
public:
    CipheringAlgorithm();
    virtual ~CipheringAlgorithm();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// CipheringAlgorithm members


protected:
};

}
}
}
}

#endif /* CipheringAlgorithm_H_ */
