/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * GnssPositioningMethodAndUsage.h
 *
 * 
 */

#ifndef GnssPositioningMethodAndUsage_H_
#define GnssPositioningMethodAndUsage_H_


#include "ModelBase.h"

#include "Usage.h"
#include "GnssId.h"
#include "PositioningMode.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  GnssPositioningMethodAndUsage
    : public ModelBase
{
public:
    GnssPositioningMethodAndUsage();
    virtual ~GnssPositioningMethodAndUsage();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// GnssPositioningMethodAndUsage members

    /// <summary>
    /// 
    /// </summary>
    PositioningMode getMode() const;
    void setMode(PositioningMode const& value);
        /// <summary>
    /// 
    /// </summary>
    GnssId getGnss() const;
    void setGnss(GnssId const& value);
        /// <summary>
    /// 
    /// </summary>
    Usage getUsage() const;
    void setUsage(Usage const& value);
    
protected:
    PositioningMode m_Mode;

    GnssId m_Gnss;

    Usage m_Usage;

};

}
}
}
}

#endif /* GnssPositioningMethodAndUsage_H_ */
