/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Guami.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Guami::Guami()
{
    m_AmfId = "";
    
}

Guami::~Guami()
{
}

void Guami::validate()
{
    // TODO: implement validation
}

nlohmann::json Guami::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["plmnId"] = ModelBase::toJson(m_PlmnId);
    val["amfId"] = ModelBase::toJson(m_AmfId);
    

    return val;
}

void Guami::fromJson(const nlohmann::json& val)
{
    setAmfId(val.at("amfId"));
    
}


PlmnId Guami::getPlmnId() const
{
    return m_PlmnId;
}
void Guami::setPlmnId(PlmnId const& value)
{
    m_PlmnId = value;
    
}
std::string Guami::getAmfId() const
{
    return m_AmfId;
}
void Guami::setAmfId(std::string const& value)
{
    m_AmfId = value;
    
}

}
}
}
}

