/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "HorizontalWithVerticalVelocity.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

HorizontalWithVerticalVelocity::HorizontalWithVerticalVelocity()
{
    m_HSpeed = 0.0f;
    m_Bearing = 0;
    m_VSpeed = 0.0f;
    
}

HorizontalWithVerticalVelocity::~HorizontalWithVerticalVelocity()
{
}

void HorizontalWithVerticalVelocity::validate()
{
    // TODO: implement validation
}

nlohmann::json HorizontalWithVerticalVelocity::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["hSpeed"] = m_HSpeed;
    val["bearing"] = m_Bearing;
    val["vSpeed"] = m_VSpeed;
    val["vDirection"] = ModelBase::toJson(m_VDirection);
    

    return val;
}

void HorizontalWithVerticalVelocity::fromJson(const nlohmann::json& val)
{
    setHSpeed(val.at("hSpeed"));
    setBearing(val.at("bearing"));
    setVSpeed(val.at("vSpeed"));
    
}


float HorizontalWithVerticalVelocity::getHSpeed() const
{
    return m_HSpeed;
}
void HorizontalWithVerticalVelocity::setHSpeed(float const value)
{
    m_HSpeed = value;
    
}
int32_t HorizontalWithVerticalVelocity::getBearing() const
{
    return m_Bearing;
}
void HorizontalWithVerticalVelocity::setBearing(int32_t const value)
{
    m_Bearing = value;
    
}
float HorizontalWithVerticalVelocity::getVSpeed() const
{
    return m_VSpeed;
}
void HorizontalWithVerticalVelocity::setVSpeed(float const value)
{
    m_VSpeed = value;
    
}
VerticalDirection HorizontalWithVerticalVelocity::getVDirection() const
{
    return m_VDirection;
}
void HorizontalWithVerticalVelocity::setVDirection(VerticalDirection const& value)
{
    m_VDirection = value;
    
}

}
}
}
}

