/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * HorizontalVelocity.h
 *
 * 
 */

#ifndef HorizontalVelocity_H_
#define HorizontalVelocity_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  HorizontalVelocity
    : public ModelBase
{
public:
    HorizontalVelocity();
    virtual ~HorizontalVelocity();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// HorizontalVelocity members

    /// <summary>
    /// 
    /// </summary>
    float getHSpeed() const;
    void setHSpeed(float const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getBearing() const;
    void setBearing(int32_t const value);
    
protected:
    float m_HSpeed;

    int32_t m_Bearing;

};

}
}
}
}

#endif /* HorizontalVelocity_H_ */
