/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LcsPriority.h
 *
 * 
 */

#ifndef LcsPriority_H_
#define LcsPriority_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  LcsPriority
    : public ModelBase
{
public:
    LcsPriority();
    virtual ~LcsPriority();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// LcsPriority members


protected:
};

}
}
}
}

#endif /* LcsPriority_H_ */
