/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "LocationFilter.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

LocationFilter::LocationFilter()
{
    
}

LocationFilter::~LocationFilter()
{
}

void LocationFilter::validate()
{
    // TODO: implement validation
}

nlohmann::json LocationFilter::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void LocationFilter::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

