/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LocationEvent.h
 *
 * 
 */

#ifndef LocationEvent_H_
#define LocationEvent_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  LocationEvent
    : public ModelBase
{
public:
    LocationEvent();
    virtual ~LocationEvent();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// LocationEvent members


protected:
};

}
}
}
}

#endif /* LocationEvent_H_ */
