/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N1MessageContainer.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N1MessageContainer::N1MessageContainer()
{
    m_LmfId = "";
    m_LmfIdIsSet = false;
    
}

N1MessageContainer::~N1MessageContainer()
{
}

void N1MessageContainer::validate()
{
    // TODO: implement validation
}

nlohmann::json N1MessageContainer::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["n1MessageClass"] = ModelBase::toJson(m_N1MessageClass);
    val["n1MessageContent"] = ModelBase::toJson(m_N1MessageContent);
    if(m_LmfIdIsSet)
    {
        val["lmfId"] = ModelBase::toJson(m_LmfId);
    }
    

    return val;
}

void N1MessageContainer::fromJson(const nlohmann::json& val)
{
    if(val.find("lmfId") != val.end())
    {
        setLmfId(val.at("lmfId"));
    }
    
}


N1MessageClass N1MessageContainer::getN1MessageClass() const
{
    return m_N1MessageClass;
}
void N1MessageContainer::setN1MessageClass(N1MessageClass const& value)
{
    m_N1MessageClass = value;
    
}
RefToBinaryData N1MessageContainer::getN1MessageContent() const
{
    return m_N1MessageContent;
}
void N1MessageContainer::setN1MessageContent(RefToBinaryData const& value)
{
    m_N1MessageContent = value;
    
}
std::string N1MessageContainer::getLmfId() const
{
    return m_LmfId;
}
void N1MessageContainer::setLmfId(std::string const& value)
{
    m_LmfId = value;
    m_LmfIdIsSet = true;
}
bool N1MessageContainer::lmfIdIsSet() const
{
    return m_LmfIdIsSet;
}
void N1MessageContainer::unsetLmfId()
{
    m_LmfIdIsSet = false;
}

}
}
}
}

