/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N1MessageClass.h
 *
 * 
 */

#ifndef N1MessageClass_H_
#define N1MessageClass_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  N1MessageClass
    : public ModelBase
{
public:
    N1MessageClass();
    virtual ~N1MessageClass();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// N1MessageClass members


protected:
};

}
}
}
}

#endif /* N1MessageClass_H_ */
