/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N1N2MessageTransferRspData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N1N2MessageTransferRspData::N1N2MessageTransferRspData()
{
    m_SupportedFeatures = "";
    m_SupportedFeaturesIsSet = false;
    
}

N1N2MessageTransferRspData::~N1N2MessageTransferRspData()
{
}

void N1N2MessageTransferRspData::validate()
{
    // TODO: implement validation
}

nlohmann::json N1N2MessageTransferRspData::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["cause"] = ModelBase::toJson(m_Cause);
    if(m_SupportedFeaturesIsSet)
    {
        val["supportedFeatures"] = ModelBase::toJson(m_SupportedFeatures);
    }
    

    return val;
}

void N1N2MessageTransferRspData::fromJson(const nlohmann::json& val)
{
    if(val.find("supportedFeatures") != val.end())
    {
        setSupportedFeatures(val.at("supportedFeatures"));
    }
    
}


N1N2MessageTransferCause N1N2MessageTransferRspData::getCause() const
{
    return m_Cause;
}
void N1N2MessageTransferRspData::setCause(N1N2MessageTransferCause const& value)
{
    m_Cause = value;
    
}
std::string N1N2MessageTransferRspData::getSupportedFeatures() const
{
    return m_SupportedFeatures;
}
void N1N2MessageTransferRspData::setSupportedFeatures(std::string const& value)
{
    m_SupportedFeatures = value;
    m_SupportedFeaturesIsSet = true;
}
bool N1N2MessageTransferRspData::supportedFeaturesIsSet() const
{
    return m_SupportedFeaturesIsSet;
}
void N1N2MessageTransferRspData::unsetSupportedFeatures()
{
    m_SupportedFeaturesIsSet = false;
}

}
}
}
}

