/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N2InformationClass.h
 *
 * 
 */

#ifndef N2InformationClass_H_
#define N2InformationClass_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  N2InformationClass
    : public ModelBase
{
public:
    N2InformationClass();
    virtual ~N2InformationClass();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// N2InformationClass members


protected:
};

}
}
}
}

#endif /* N2InformationClass_H_ */
