/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N2InformationTransferError.h
 *
 * 
 */

#ifndef N2InformationTransferError_H_
#define N2InformationTransferError_H_


#include "ModelBase.h"

#include "ProblemDetails.h"
#include "PWSErrorData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  N2InformationTransferError
    : public ModelBase
{
public:
    N2InformationTransferError();
    virtual ~N2InformationTransferError();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// N2InformationTransferError members

    /// <summary>
    /// 
    /// </summary>
    ProblemDetails getError() const;
    void setError(ProblemDetails const& value);
        /// <summary>
    /// 
    /// </summary>
    PWSErrorData getPwdErrorInfo() const;
    void setPwdErrorInfo(PWSErrorData const& value);
    bool pwdErrorInfoIsSet() const;
    void unsetPwdErrorInfo();

protected:
    ProblemDetails m_Error;

    PWSErrorData m_PwdErrorInfo;
    bool m_PwdErrorInfoIsSet;
};

}
}
}
}

#endif /* N2InformationTransferError_H_ */
