/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N2InformationTransferResult.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N2InformationTransferResult::N2InformationTransferResult()
{
    
}

N2InformationTransferResult::~N2InformationTransferResult()
{
}

void N2InformationTransferResult::validate()
{
    // TODO: implement validation
}

nlohmann::json N2InformationTransferResult::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void N2InformationTransferResult::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

