/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NsiInformation.h
 *
 * 
 */

#ifndef NsiInformation_H_
#define NsiInformation_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  NsiInformation
    : public ModelBase
{
public:
    NsiInformation();
    virtual ~NsiInformation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// NsiInformation members

    /// <summary>
    /// 
    /// </summary>
    std::string getNsiId() const;
    void setNsiId(std::string const& value);
    bool nsiIdIsSet() const;
    void unsetNsiId();

protected:
    std::string m_NsiId;
    bool m_NsiIdIsSet;
};

}
}
}
}

#endif /* NsiInformation_H_ */
