/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NsiInformation.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

NsiInformation::NsiInformation()
{
    m_NsiId = "";
    m_NsiIdIsSet = false;
    
}

NsiInformation::~NsiInformation()
{
}

void NsiInformation::validate()
{
    // TODO: implement validation
}

nlohmann::json NsiInformation::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_NsiIdIsSet)
    {
        val["nsiId"] = ModelBase::toJson(m_NsiId);
    }
    

    return val;
}

void NsiInformation::fromJson(const nlohmann::json& val)
{
    if(val.find("nsiId") != val.end())
    {
        setNsiId(val.at("nsiId"));
    }
    
}


std::string NsiInformation::getNsiId() const
{
    return m_NsiId;
}
void NsiInformation::setNsiId(std::string const& value)
{
    m_NsiId = value;
    m_NsiIdIsSet = true;
}
bool NsiInformation::nsiIdIsSet() const
{
    return m_NsiIdIsSet;
}
void NsiInformation::unsetNsiId()
{
    m_NsiIdIsSet = false;
}

}
}
}
}

