/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NssaiMapping.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

NssaiMapping::NssaiMapping()
{
    
}

NssaiMapping::~NssaiMapping()
{
}

void NssaiMapping::validate()
{
    // TODO: implement validation
}

nlohmann::json NssaiMapping::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["mappedSnssai"] = ModelBase::toJson(m_MappedSnssai);
    val["hSnssai"] = ModelBase::toJson(m_HSnssai);
    

    return val;
}

void NssaiMapping::fromJson(const nlohmann::json& val)
{
    
}


Snssai_2 NssaiMapping::getMappedSnssai() const
{
    return m_MappedSnssai;
}
void NssaiMapping::setMappedSnssai(Snssai_2 const& value)
{
    m_MappedSnssai = value;
    
}
Snssai_2 NssaiMapping::getHSnssai() const
{
    return m_HSnssai;
}
void NssaiMapping::setHSnssai(Snssai_2 const& value)
{
    m_HSnssai = value;
    
}

}
}
}
}

