/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NssaiMapping.h
 *
 * 
 */

#ifndef NssaiMapping_H_
#define NssaiMapping_H_


#include "ModelBase.h"

#include "Snssai_2.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  NssaiMapping
    : public ModelBase
{
public:
    NssaiMapping();
    virtual ~NssaiMapping();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// NssaiMapping members

    /// <summary>
    /// 
    /// </summary>
    Snssai_2 getMappedSnssai() const;
    void setMappedSnssai(Snssai_2 const& value);
        /// <summary>
    /// 
    /// </summary>
    Snssai_2 getHSnssai() const;
    void setHSnssai(Snssai_2 const& value);
    
protected:
    Snssai_2 m_MappedSnssai;

    Snssai_2 m_HSnssai;

};

}
}
}
}

#endif /* NssaiMapping_H_ */
