/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PWSErrorData.h
 *
 * 
 */

#ifndef PWSErrorData_H_
#define PWSErrorData_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  PWSErrorData
    : public ModelBase
{
public:
    PWSErrorData();
    virtual ~PWSErrorData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PWSErrorData members

    /// <summary>
    /// 
    /// </summary>
    int32_t getNamfCause() const;
    void setNamfCause(int32_t const value);
    
protected:
    int32_t m_NamfCause;

};

}
}
}
}

#endif /* PWSErrorData_H_ */
