/**
* AMF MT Service
* AMF Mobile Termination Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RatType.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

RatType::RatType()
{
    
}

RatType::~RatType()
{
}

void RatType::validate()
{
    // TODO: implement validation
}

nlohmann::json RatType::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void RatType::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

