/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RefToBinaryData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

RefToBinaryData::RefToBinaryData()
{
    m_ContentId = "";
    
}

RefToBinaryData::~RefToBinaryData()
{
}

void RefToBinaryData::validate()
{
    // TODO: implement validation
}

nlohmann::json RefToBinaryData::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["contentId"] = ModelBase::toJson(m_ContentId);
    

    return val;
}

void RefToBinaryData::fromJson(const nlohmann::json& val)
{
    setContentId(val.at("contentId"));
    
}


std::string RefToBinaryData::getContentId() const
{
    return m_ContentId;
}
void RefToBinaryData::setContentId(std::string const& value)
{
    m_ContentId = value;
    
}

}
}
}
}

