/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RmInfo.h
 *
 * 
 */

#ifndef RmInfo_H_
#define RmInfo_H_


#include "ModelBase.h"

#include "RmState.h"
#include "AccessType.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  RmInfo
    : public ModelBase
{
public:
    RmInfo();
    virtual ~RmInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// RmInfo members

    /// <summary>
    /// 
    /// </summary>
    RmState getRmState() const;
    void setRmState(RmState const& value);
        /// <summary>
    /// 
    /// </summary>
    AccessType getAccessType() const;
    void setAccessType(AccessType const& value);
    
protected:
    RmState m_RmState;

    AccessType m_AccessType;

};

}
}
}
}

#endif /* RmInfo_H_ */
