/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ScType.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ScType::ScType()
{
    
}

ScType::~ScType()
{
}

void ScType::validate()
{
    // TODO: implement validation
}

nlohmann::json ScType::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void ScType::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

