/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SupportedGADShapes.h
 *
 * 
 */

#ifndef SupportedGADShapes_H_
#define SupportedGADShapes_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  SupportedGADShapes
    : public ModelBase
{
public:
    SupportedGADShapes();
    virtual ~SupportedGADShapes();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// SupportedGADShapes members


protected:
};

}
}
}
}

#endif /* SupportedGADShapes_H_ */
