/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UeContextCreateError.h
 *
 * 
 */

#ifndef UeContextCreateError_H_
#define UeContextCreateError_H_


#include "ModelBase.h"

#include "ProblemDetails.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  UeContextCreateError
    : public ModelBase
{
public:
    UeContextCreateError();
    virtual ~UeContextCreateError();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// UeContextCreateError members

    /// <summary>
    /// 
    /// </summary>
    ProblemDetails getError() const;
    void setError(ProblemDetails const& value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getNgapCause() const;
    void setNgapCause(int32_t const value);
    bool ngapCauseIsSet() const;
    void unsetNgapCause();

protected:
    ProblemDetails m_Error;

    int32_t m_NgapCause;
    bool m_NgapCauseIsSet;
};

}
}
}
}

#endif /* UeContextCreateError_H_ */
