/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UeContextTransferRspData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

UeContextTransferRspData::UeContextTransferRspData()
{
    m_RegCompleteNotifyUri = "";
    m_SupportedFeatures = "";
    m_SupportedFeaturesIsSet = false;
    
}

UeContextTransferRspData::~UeContextTransferRspData()
{
}

void UeContextTransferRspData::validate()
{
    // TODO: implement validation
}

nlohmann::json UeContextTransferRspData::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["ueContext"] = ModelBase::toJson(m_UeContext);
    val["regCompleteNotifyUri"] = ModelBase::toJson(m_RegCompleteNotifyUri);
    if(m_SupportedFeaturesIsSet)
    {
        val["supportedFeatures"] = ModelBase::toJson(m_SupportedFeatures);
    }
    

    return val;
}

void UeContextTransferRspData::fromJson(const nlohmann::json& val)
{
    setRegCompleteNotifyUri(val.at("regCompleteNotifyUri"));
    if(val.find("supportedFeatures") != val.end())
    {
        setSupportedFeatures(val.at("supportedFeatures"));
    }
    
}


UeContext UeContextTransferRspData::getUeContext() const
{
    return m_UeContext;
}
void UeContextTransferRspData::setUeContext(UeContext const& value)
{
    m_UeContext = value;
    
}
std::string UeContextTransferRspData::getRegCompleteNotifyUri() const
{
    return m_RegCompleteNotifyUri;
}
void UeContextTransferRspData::setRegCompleteNotifyUri(std::string const& value)
{
    m_RegCompleteNotifyUri = value;
    
}
std::string UeContextTransferRspData::getSupportedFeatures() const
{
    return m_SupportedFeatures;
}
void UeContextTransferRspData::setSupportedFeatures(std::string const& value)
{
    m_SupportedFeatures = value;
    m_SupportedFeaturesIsSet = true;
}
bool UeContextTransferRspData::supportedFeaturesIsSet() const
{
    return m_SupportedFeaturesIsSet;
}
void UeContextTransferRspData::unsetSupportedFeatures()
{
    m_SupportedFeaturesIsSet = false;
}

}
}
}
}

