/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UncertaintyEllipse.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

UncertaintyEllipse::UncertaintyEllipse()
{
    m_SemiMajor = 0.0f;
    m_SemiMinor = 0.0f;
    m_OrientationMajor = 0;
    
}

UncertaintyEllipse::~UncertaintyEllipse()
{
}

void UncertaintyEllipse::validate()
{
    // TODO: implement validation
}

nlohmann::json UncertaintyEllipse::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["semiMajor"] = m_SemiMajor;
    val["semiMinor"] = m_SemiMinor;
    val["orientationMajor"] = m_OrientationMajor;
    

    return val;
}

void UncertaintyEllipse::fromJson(const nlohmann::json& val)
{
    setSemiMajor(val.at("semiMajor"));
    setSemiMinor(val.at("semiMinor"));
    setOrientationMajor(val.at("orientationMajor"));
    
}


float UncertaintyEllipse::getSemiMajor() const
{
    return m_SemiMajor;
}
void UncertaintyEllipse::setSemiMajor(float const value)
{
    m_SemiMajor = value;
    
}
float UncertaintyEllipse::getSemiMinor() const
{
    return m_SemiMinor;
}
void UncertaintyEllipse::setSemiMinor(float const value)
{
    m_SemiMinor = value;
    
}
int32_t UncertaintyEllipse::getOrientationMajor() const
{
    return m_OrientationMajor;
}
void UncertaintyEllipse::setOrientationMajor(int32_t const value)
{
    m_OrientationMajor = value;
    
}

}
}
}
}

