/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UncertaintyEllipse.h
 *
 * 
 */

#ifndef UncertaintyEllipse_H_
#define UncertaintyEllipse_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  UncertaintyEllipse
    : public ModelBase
{
public:
    UncertaintyEllipse();
    virtual ~UncertaintyEllipse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// UncertaintyEllipse members

    /// <summary>
    /// 
    /// </summary>
    float getSemiMajor() const;
    void setSemiMajor(float const value);
        /// <summary>
    /// 
    /// </summary>
    float getSemiMinor() const;
    void setSemiMinor(float const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getOrientationMajor() const;
    void setOrientationMajor(int32_t const value);
    
protected:
    float m_SemiMajor;

    float m_SemiMinor;

    int32_t m_OrientationMajor;

};

}
}
}
}

#endif /* UncertaintyEllipse_H_ */
