/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Usage.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Usage::Usage()
{
    
}

Usage::~Usage()
{
}

void Usage::validate()
{
    // TODO: implement validation
}

nlohmann::json Usage::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void Usage::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

