/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "ModifySubscriptionApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

ModifySubscriptionApi::ModifySubscriptionApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void ModifySubscriptionApi::init() {
    setupRoutes();
}

void ModifySubscriptionApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Patch(*router, base + "/subscriptions/:subscriptionId", Routes::bind(&ModifySubscriptionApi::modify_subscription_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&ModifySubscriptionApi::modify_subscription_api_default_handler, this));
}

void ModifySubscriptionApi::modify_subscription_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    // Getting the path params
    auto subscriptionId = request.param(":subscriptionId").as<std::string>();
    
    // Getting the body param
    std::vector<Object> object;
    
    try {
      nlohmann::json request_body = nlohmann::json::parse(request.body());
      object =   ArrayHelper::fromJson<Object>(request_body);
      this->modify_subscription(subscriptionId, object, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void ModifySubscriptionApi::modify_subscription_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

