/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AllowedSNssai.h
 *
 * 
 */

#ifndef AllowedSNssai_H_
#define AllowedSNssai_H_


#include "ModelBase.h"

#include "NsiInformation.h"
#include "Snssai.h"
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AllowedSNssai
    : public ModelBase
{
public:
    AllowedSNssai();
    virtual ~AllowedSNssai();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AllowedSNssai members

    /// <summary>
    /// 
    /// </summary>
    Snssai getAllowedSNssai() const;
    void setAllowedSNssai(Snssai const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<NsiInformation>& getNsiInformation();
    bool nsiInformationIsSet() const;
    void unsetNsiInformation();
    /// <summary>
    /// 
    /// </summary>
    Snssai getMappedHomeSNssai() const;
    void setMappedHomeSNssai(Snssai const& value);
    bool mappedHomeSNssaiIsSet() const;
    void unsetMappedHomeSNssai();

protected:
    Snssai m_AllowedSNssai;

    std::vector<NsiInformation> m_NsiInformation;
    bool m_NsiInformationIsSet;
    Snssai m_MappedHomeSNssai;
    bool m_MappedHomeSNssaiIsSet;
};

}
}
}
}

#endif /* AllowedSNssai_H_ */
