/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Arp_2.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Arp_2::Arp_2()
{
    m_PriorityLevel = 0;
    
}

Arp_2::~Arp_2()
{
}

void Arp_2::validate()
{
    // TODO: implement validation
}

nlohmann::json Arp_2::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["priorityLevel"] = m_PriorityLevel;
    val["preemptCap"] = ModelBase::toJson(m_PreemptCap);
    val["preemptVuln"] = ModelBase::toJson(m_PreemptVuln);
    

    return val;
}

void Arp_2::fromJson(const nlohmann::json& val)
{
    setPriorityLevel(val.at("priorityLevel"));
    
}


int32_t Arp_2::getPriorityLevel() const
{
    return m_PriorityLevel;
}
void Arp_2::setPriorityLevel(int32_t const value)
{
    m_PriorityLevel = value;
    
}
PreemptionCapability Arp_2::getPreemptCap() const
{
    return m_PreemptCap;
}
void Arp_2::setPreemptCap(PreemptionCapability const& value)
{
    m_PreemptCap = value;
    
}
PreemptionVulnerability Arp_2::getPreemptVuln() const
{
    return m_PreemptVuln;
}
void Arp_2::setPreemptVuln(PreemptionVulnerability const& value)
{
    m_PreemptVuln = value;
    
}

}
}
}
}

