/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AssignEbiFailed.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

AssignEbiFailed::AssignEbiFailed()
{
    m_PduSessionId = 0;
    m_FailedArpListIsSet = false;
    
}

AssignEbiFailed::~AssignEbiFailed()
{
}

void AssignEbiFailed::validate()
{
    // TODO: implement validation
}

nlohmann::json AssignEbiFailed::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["pduSessionId"] = m_PduSessionId;
    {
        nlohmann::json jsonArray;
        for( auto& item : m_FailedArpList )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            val["failedArpList"] = jsonArray;
        } 
    }
    

    return val;
}

void AssignEbiFailed::fromJson(const nlohmann::json& val)
{
    setPduSessionId(val.at("pduSessionId"));
    {
        m_FailedArpList.clear();
        if(val.find("failedArpList") != val.end())
        {
            for( auto& item : val["failedArpList"] )
            {
                
                if(item.is_null())
                {
                    m_FailedArpList.push_back( Arp() );
                }
                else
                {
                    Arp newItem;
                    newItem.fromJson(item);
                    m_FailedArpList.push_back( newItem );
                }
                
            }
        }
    }
    
}


int32_t AssignEbiFailed::getPduSessionId() const
{
    return m_PduSessionId;
}
void AssignEbiFailed::setPduSessionId(int32_t const value)
{
    m_PduSessionId = value;
    
}
std::vector<Arp>& AssignEbiFailed::getFailedArpList()
{
    return m_FailedArpList;
}
bool AssignEbiFailed::failedArpListIsSet() const
{
    return m_FailedArpListIsSet;
}
void AssignEbiFailed::unsetFailedArpList()
{
    m_FailedArpListIsSet = false;
}

}
}
}
}

