/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "IntegrityAlgorithm.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

IntegrityAlgorithm::IntegrityAlgorithm()
{
    
}

IntegrityAlgorithm::~IntegrityAlgorithm()
{
}

void IntegrityAlgorithm::validate()
{
    // TODO: implement validation
}

nlohmann::json IntegrityAlgorithm::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void IntegrityAlgorithm::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

