/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N1MessageContainer.h
 *
 * 
 */

#ifndef N1MessageContainer_H_
#define N1MessageContainer_H_


#include "ModelBase.h"

#include "N1MessageClass.h"
#include "RefToBinaryData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  N1MessageContainer
    : public ModelBase
{
public:
    N1MessageContainer();
    virtual ~N1MessageContainer();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// N1MessageContainer members

    /// <summary>
    /// 
    /// </summary>
    N1MessageClass getN1MessageClass() const;
    void setN1MessageClass(N1MessageClass const& value);
        /// <summary>
    /// 
    /// </summary>
    RefToBinaryData getN1MessageContent() const;
    void setN1MessageContent(RefToBinaryData const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getLmfId() const;
    void setLmfId(std::string const& value);
    bool lmfIdIsSet() const;
    void unsetLmfId();

protected:
    N1MessageClass m_N1MessageClass;

    RefToBinaryData m_N1MessageContent;

    std::string m_LmfId;
    bool m_LmfIdIsSet;
};

}
}
}
}

#endif /* N1MessageContainer_H_ */
