/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N1N2MsgTxfrFailureNotification.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N1N2MsgTxfrFailureNotification::N1N2MsgTxfrFailureNotification()
{
    m_N1n2MsgDataUri = "";
    
}

N1N2MsgTxfrFailureNotification::~N1N2MsgTxfrFailureNotification()
{
}

void N1N2MsgTxfrFailureNotification::validate()
{
    // TODO: implement validation
}

nlohmann::json N1N2MsgTxfrFailureNotification::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["cause"] = ModelBase::toJson(m_Cause);
    val["n1n2MsgDataUri"] = ModelBase::toJson(m_N1n2MsgDataUri);
    

    return val;
}

void N1N2MsgTxfrFailureNotification::fromJson(const nlohmann::json& val)
{
    setN1n2MsgDataUri(val.at("n1n2MsgDataUri"));
    
}


N1N2MessageTransferCause N1N2MsgTxfrFailureNotification::getCause() const
{
    return m_Cause;
}
void N1N2MsgTxfrFailureNotification::setCause(N1N2MessageTransferCause const& value)
{
    m_Cause = value;
    
}
std::string N1N2MsgTxfrFailureNotification::getN1n2MsgDataUri() const
{
    return m_N1n2MsgDataUri;
}
void N1N2MsgTxfrFailureNotification::setN1n2MsgDataUri(std::string const& value)
{
    m_N1n2MsgDataUri = value;
    
}

}
}
}
}

