/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N1N2MsgTxfrErrDetail.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N1N2MsgTxfrErrDetail::N1N2MsgTxfrErrDetail()
{
    m_RetryAfter = 0;
    m_RetryAfterIsSet = false;
    m_HighestPrioArpIsSet = false;
    
}

N1N2MsgTxfrErrDetail::~N1N2MsgTxfrErrDetail()
{
}

void N1N2MsgTxfrErrDetail::validate()
{
    // TODO: implement validation
}

nlohmann::json N1N2MsgTxfrErrDetail::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_RetryAfterIsSet)
    {
        val["retryAfter"] = m_RetryAfter;
    }
    if(m_HighestPrioArpIsSet)
    {
        val["highestPrioArp"] = ModelBase::toJson(m_HighestPrioArp);
    }
    

    return val;
}

void N1N2MsgTxfrErrDetail::fromJson(const nlohmann::json& val)
{
    if(val.find("retryAfter") != val.end())
    {
        setRetryAfter(val.at("retryAfter"));
    }
    if(val.find("highestPrioArp") != val.end())
    {
        if(!val["highestPrioArp"].is_null())
        {
            Arp newItem;
            newItem.fromJson(val["highestPrioArp"]);
            setHighestPrioArp( newItem );
        }
        
    }
    
}


int32_t N1N2MsgTxfrErrDetail::getRetryAfter() const
{
    return m_RetryAfter;
}
void N1N2MsgTxfrErrDetail::setRetryAfter(int32_t const value)
{
    m_RetryAfter = value;
    m_RetryAfterIsSet = true;
}
bool N1N2MsgTxfrErrDetail::retryAfterIsSet() const
{
    return m_RetryAfterIsSet;
}
void N1N2MsgTxfrErrDetail::unsetRetryAfter()
{
    m_RetryAfterIsSet = false;
}
Arp N1N2MsgTxfrErrDetail::getHighestPrioArp() const
{
    return m_HighestPrioArp;
}
void N1N2MsgTxfrErrDetail::setHighestPrioArp(Arp const& value)
{
    m_HighestPrioArp = value;
    m_HighestPrioArpIsSet = true;
}
bool N1N2MsgTxfrErrDetail::highestPrioArpIsSet() const
{
    return m_HighestPrioArpIsSet;
}
void N1N2MsgTxfrErrDetail::unsetHighestPrioArp()
{
    m_HighestPrioArpIsSet = false;
}

}
}
}
}

