/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N2InfoContent.h
 *
 * 
 */

#ifndef N2InfoContent_H_
#define N2InfoContent_H_


#include "ModelBase.h"

#include "RefToBinaryData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  N2InfoContent
    : public ModelBase
{
public:
    N2InfoContent();
    virtual ~N2InfoContent();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// N2InfoContent members

    /// <summary>
    /// 
    /// </summary>
    int32_t getNgapMessageType() const;
    void setNgapMessageType(int32_t const value);
    bool ngapMessageTypeIsSet() const;
    void unsetNgapMessageType();
    /// <summary>
    /// 
    /// </summary>
    int32_t getNgapIeType() const;
    void setNgapIeType(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    RefToBinaryData getNgapData() const;
    void setNgapData(RefToBinaryData const& value);
    
protected:
    int32_t m_NgapMessageType;
    bool m_NgapMessageTypeIsSet;
    int32_t m_NgapIeType;

    RefToBinaryData m_NgapData;

};

}
}
}
}

#endif /* N2InfoContent_H_ */
