/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N2InformationClass.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N2InformationClass::N2InformationClass()
{
    
}

N2InformationClass::~N2InformationClass()
{
}

void N2InformationClass::validate()
{
    // TODO: implement validation
}

nlohmann::json N2InformationClass::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void N2InformationClass::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

