/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N2InformationTransferError.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N2InformationTransferError::N2InformationTransferError()
{
    m_PwdErrorInfoIsSet = false;
    
}

N2InformationTransferError::~N2InformationTransferError()
{
}

void N2InformationTransferError::validate()
{
    // TODO: implement validation
}

nlohmann::json N2InformationTransferError::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["error"] = ModelBase::toJson(m_Error);
    if(m_PwdErrorInfoIsSet)
    {
        val["pwdErrorInfo"] = ModelBase::toJson(m_PwdErrorInfo);
    }
    

    return val;
}

void N2InformationTransferError::fromJson(const nlohmann::json& val)
{
    if(val.find("pwdErrorInfo") != val.end())
    {
        if(!val["pwdErrorInfo"].is_null())
        {
            PWSErrorData newItem;
            newItem.fromJson(val["pwdErrorInfo"]);
            setPwdErrorInfo( newItem );
        }
        
    }
    
}


ProblemDetails N2InformationTransferError::getError() const
{
    return m_Error;
}
void N2InformationTransferError::setError(ProblemDetails const& value)
{
    m_Error = value;
    
}
PWSErrorData N2InformationTransferError::getPwdErrorInfo() const
{
    return m_PwdErrorInfo;
}
void N2InformationTransferError::setPwdErrorInfo(PWSErrorData const& value)
{
    m_PwdErrorInfo = value;
    m_PwdErrorInfoIsSet = true;
}
bool N2InformationTransferError::pwdErrorInfoIsSet() const
{
    return m_PwdErrorInfoIsSet;
}
void N2InformationTransferError::unsetPwdErrorInfo()
{
    m_PwdErrorInfoIsSet = false;
}

}
}
}
}

