/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NasSecurityMode.h
 *
 * 
 */

#ifndef NasSecurityMode_H_
#define NasSecurityMode_H_


#include "ModelBase.h"

#include "IntegrityAlgorithm.h"
#include "CipheringAlgorithm.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  NasSecurityMode
    : public ModelBase
{
public:
    NasSecurityMode();
    virtual ~NasSecurityMode();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// NasSecurityMode members

    /// <summary>
    /// 
    /// </summary>
    IntegrityAlgorithm getIntegrityAlgorithm() const;
    void setIntegrityAlgorithm(IntegrityAlgorithm const& value);
        /// <summary>
    /// 
    /// </summary>
    CipheringAlgorithm getCipheringAlgorithm() const;
    void setCipheringAlgorithm(CipheringAlgorithm const& value);
    
protected:
    IntegrityAlgorithm m_IntegrityAlgorithm;

    CipheringAlgorithm m_CipheringAlgorithm;

};

}
}
}
}

#endif /* NasSecurityMode_H_ */
