/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NgKsi.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

NgKsi::NgKsi()
{
    m_Ksi = 0;
    
}

NgKsi::~NgKsi()
{
}

void NgKsi::validate()
{
    // TODO: implement validation
}

nlohmann::json NgKsi::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["tsc"] = ModelBase::toJson(m_Tsc);
    val["ksi"] = m_Ksi;
    

    return val;
}

void NgKsi::fromJson(const nlohmann::json& val)
{
    setKsi(val.at("ksi"));
    
}


ScType NgKsi::getTsc() const
{
    return m_Tsc;
}
void NgKsi::setTsc(ScType const& value)
{
    m_Tsc = value;
    
}
int32_t NgKsi::getKsi() const
{
    return m_Ksi;
}
void NgKsi::setKsi(int32_t const value)
{
    m_Ksi = value;
    
}

}
}
}
}

