/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NgKsi.h
 *
 * 
 */

#ifndef NgKsi_H_
#define NgKsi_H_


#include "ModelBase.h"

#include "ScType.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  NgKsi
    : public ModelBase
{
public:
    NgKsi();
    virtual ~NgKsi();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// NgKsi members

    /// <summary>
    /// 
    /// </summary>
    ScType getTsc() const;
    void setTsc(ScType const& value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getKsi() const;
    void setKsi(int32_t const value);
    
protected:
    ScType m_Tsc;

    int32_t m_Ksi;

};

}
}
}
}

#endif /* NgKsi_H_ */
