/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PlmnId_2.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PlmnId_2::PlmnId_2()
{
    m_Mcc = "";
    m_Mnc = "";
    
}

PlmnId_2::~PlmnId_2()
{
}

void PlmnId_2::validate()
{
    // TODO: implement validation
}

nlohmann::json PlmnId_2::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["mcc"] = ModelBase::toJson(m_Mcc);
    val["mnc"] = ModelBase::toJson(m_Mnc);
    

    return val;
}

void PlmnId_2::fromJson(const nlohmann::json& val)
{
    setMcc(val.at("mcc"));
    setMnc(val.at("mnc"));
    
}


std::string PlmnId_2::getMcc() const
{
    return m_Mcc;
}
void PlmnId_2::setMcc(std::string const& value)
{
    m_Mcc = value;
    
}
std::string PlmnId_2::getMnc() const
{
    return m_Mnc;
}
void PlmnId_2::setMnc(std::string const& value)
{
    m_Mnc = value;
    
}

}
}
}
}

