/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PreemptionCapability_2.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PreemptionCapability_2::PreemptionCapability_2()
{
    
}

PreemptionCapability_2::~PreemptionCapability_2()
{
}

void PreemptionCapability_2::validate()
{
    // TODO: implement validation
}

nlohmann::json PreemptionCapability_2::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void PreemptionCapability_2::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

