/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PWSErrorData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PWSErrorData::PWSErrorData()
{
    m_NamfCause = 0;
    
}

PWSErrorData::~PWSErrorData()
{
}

void PWSErrorData::validate()
{
    // TODO: implement validation
}

nlohmann::json PWSErrorData::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["namfCause"] = m_NamfCause;
    

    return val;
}

void PWSErrorData::fromJson(const nlohmann::json& val)
{
    setNamfCause(val.at("namfCause"));
    
}


int32_t PWSErrorData::getNamfCause() const
{
    return m_NamfCause;
}
void PWSErrorData::setNamfCause(int32_t const value)
{
    m_NamfCause = value;
    
}

}
}
}
}

