/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PWSResponseData.h
 *
 * 
 */

#ifndef PWSResponseData_H_
#define PWSResponseData_H_


#include "ModelBase.h"

#include "Tai.h"
#include <vector>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  PWSResponseData
    : public ModelBase
{
public:
    PWSResponseData();
    virtual ~PWSResponseData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PWSResponseData members

    /// <summary>
    /// 
    /// </summary>
    int32_t getNgapMessageType() const;
    void setNgapMessageType(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getSerialNumber() const;
    void setSerialNumber(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getMessageIdentifier() const;
    void setMessageIdentifier(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<Tai>& getUnknownTaiList();
    bool unknownTaiListIsSet() const;
    void unsetUnknownTaiList();

protected:
    int32_t m_NgapMessageType;

    int32_t m_SerialNumber;

    int32_t m_MessageIdentifier;

    std::vector<Tai> m_UnknownTaiList;
    bool m_UnknownTaiListIsSet;
};

}
}
}
}

#endif /* PWSResponseData_H_ */
