/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RefToBinaryData.h
 *
 * 
 */

#ifndef RefToBinaryData_H_
#define RefToBinaryData_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  RefToBinaryData
    : public ModelBase
{
public:
    RefToBinaryData();
    virtual ~RefToBinaryData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// RefToBinaryData members

    /// <summary>
    /// 
    /// </summary>
    std::string getContentId() const;
    void setContentId(std::string const& value);
    
protected:
    std::string m_ContentId;

};

}
}
}
}

#endif /* RefToBinaryData_H_ */
