/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SubscribedDataFilter.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SubscribedDataFilter::SubscribedDataFilter()
{
    
}

SubscribedDataFilter::~SubscribedDataFilter()
{
}

void SubscribedDataFilter::validate()
{
    // TODO: implement validation
}

nlohmann::json SubscribedDataFilter::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void SubscribedDataFilter::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

