/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UeContextTransferRspData.h
 *
 * 
 */

#ifndef UeContextTransferRspData_H_
#define UeContextTransferRspData_H_


#include "ModelBase.h"

#include "UeContext.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  UeContextTransferRspData
    : public ModelBase
{
public:
    UeContextTransferRspData();
    virtual ~UeContextTransferRspData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// UeContextTransferRspData members

    /// <summary>
    /// 
    /// </summary>
    UeContext getUeContext() const;
    void setUeContext(UeContext const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getRegCompleteNotifyUri() const;
    void setRegCompleteNotifyUri(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

protected:
    UeContext m_UeContext;

    std::string m_RegCompleteNotifyUri;

    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}
}
}
}

#endif /* UeContextTransferRspData_H_ */
