/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* ProvideLocationApiImpl.h
*
* 
*/

#ifndef PROVIDE_LOCATION_API_IMPL_H_
#define PROVIDE_LOCATION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <ProvideLocationApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "ProvideUELocation.h"
#include "RequestUELocation.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ProvideLocationApiImpl : public org::openapitools::server::api::ProvideLocationApi {
public:
    ProvideLocationApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~ProvideLocationApiImpl() {}

    void provide_location(const std::string &ueContextId, const RequestUELocation &requestUELocation, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif