/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "ProvideLocationApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

ProvideLocationApiImpl::ProvideLocationApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : ProvideLocationApi(rtr)
    { }

void ProvideLocationApiImpl::provide_location(const std::string &ueContextId, const RequestUELocation &requestUELocation, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

