/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Polygon.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Polygon::Polygon()
{
    
}

Polygon::~Polygon()
{
}

void Polygon::validate()
{
    // TODO: implement validation
}

nlohmann::json Polygon::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["shape"] = ModelBase::toJson(m_Shape);
    {
        nlohmann::json jsonArray;
        for( auto& item : m_PointList )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val["pointList"] = jsonArray;
        
    }
    

    return val;
}

void Polygon::fromJson(const nlohmann::json& val)
{
    {
        m_PointList.clear();
                    for( auto& item : val["pointList"] )
            {
                
                if(item.is_null())
                {
                    m_PointList.push_back( GeographicalCoordinates() );
                }
                else
                {
                    GeographicalCoordinates newItem;
                    newItem.fromJson(item);
                    m_PointList.push_back( newItem );
                }
                
            }
    }
    
}


SupportedGADShapes Polygon::getShape() const
{
    return m_Shape;
}
void Polygon::setShape(SupportedGADShapes const& value)
{
    m_Shape = value;
    
}
std::vector<GeographicalCoordinates>& Polygon::getPointList()
{
    return m_PointList;
}

}
}
}
}

