/**
* AMF MT Service
* AMF Mobile Termination Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "EnableUeReachabilityReqData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

EnableUeReachabilityReqData::EnableUeReachabilityReqData()
{
    m_SupportedFeatures = "";
    m_SupportedFeaturesIsSet = false;
    
}

EnableUeReachabilityReqData::~EnableUeReachabilityReqData()
{
}

void EnableUeReachabilityReqData::validate()
{
    // TODO: implement validation
}

nlohmann::json EnableUeReachabilityReqData::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["reachability"] = ModelBase::toJson(m_Reachability);
    if(m_SupportedFeaturesIsSet)
    {
        val["supportedFeatures"] = ModelBase::toJson(m_SupportedFeatures);
    }
    

    return val;
}

void EnableUeReachabilityReqData::fromJson(const nlohmann::json& val)
{
    if(val.find("supportedFeatures") != val.end())
    {
        setSupportedFeatures(val.at("supportedFeatures"));
    }
    
}


UeReachability EnableUeReachabilityReqData::getReachability() const
{
    return m_Reachability;
}
void EnableUeReachabilityReqData::setReachability(UeReachability const& value)
{
    m_Reachability = value;
    
}
std::string EnableUeReachabilityReqData::getSupportedFeatures() const
{
    return m_SupportedFeatures;
}
void EnableUeReachabilityReqData::setSupportedFeatures(std::string const& value)
{
    m_SupportedFeatures = value;
    m_SupportedFeaturesIsSet = true;
}
bool EnableUeReachabilityReqData::supportedFeaturesIsSet() const
{
    return m_SupportedFeaturesIsSet;
}
void EnableUeReachabilityReqData::unsetSupportedFeatures()
{
    m_SupportedFeaturesIsSet = false;
}

}
}
}
}

