/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* EBIAssignmentApiImpl.h
*
* 
*/

#ifndef EBI_ASSIGNMENT_API_IMPL_H_
#define EBI_ASSIGNMENT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <EBIAssignmentApi.h>

#include <pistache/optional.h>

#include "AssignEbi.h"
#include "AssignEbiError.h"
#include "AssignedEbi.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class EBIAssignmentApiImpl : public org::openapitools::server::api::EBIAssignmentApi {
public:
    EBIAssignmentApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~EBIAssignmentApiImpl() {}

    void e_bi_assignment(const std::string &ueContextId, const AssignEbi &assignEbi, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif