/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "N1N2MessageTransferApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

N1N2MessageTransferApiImpl::N1N2MessageTransferApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : N1N2MessageTransferApi(rtr)
    { }

void N1N2MessageTransferApiImpl::n1_n2_message_transfer(const std::string &ueContextId, const N1N2MessageData &n1N2MessageData, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

