/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* N1N2MessageUnSubscribeApiImpl.h
*
* 
*/

#ifndef N1_N2_MESSAGE_UN_SUBSCRIBE_API_IMPL_H_
#define N1_N2_MESSAGE_UN_SUBSCRIBE_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <N1N2MessageUnSubscribeApi.h>

#include <pistache/optional.h>

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {



class N1N2MessageUnSubscribeApiImpl : public org::openapitools::server::api::N1N2MessageUnSubscribeApi {
public:
    N1N2MessageUnSubscribeApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~N1N2MessageUnSubscribeApiImpl() {}

    void n1_n2_message_un_subscribe(const std::string &subscriptionId, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif