/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* ReleaseUEContxtApiImpl.h
*
* 
*/

#ifndef RELEASE_UE_CONTXT_API_IMPL_H_
#define RELEASE_UE_CONTXT_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <ReleaseUEContxtApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "UEContextRelease.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class ReleaseUEContxtApiImpl : public org::openapitools::server::api::ReleaseUEContxtApi {
public:
    ReleaseUEContxtApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~ReleaseUEContxtApiImpl() {}

    void release_ue_context(const std::string &ueContextId, const UEContextRelease &uEContextRelease, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif