/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "ReleaseUEContxtApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

ReleaseUEContxtApiImpl::ReleaseUEContxtApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : ReleaseUEContxtApi(rtr)
    { }

void ReleaseUEContxtApiImpl::release_ue_context(const std::string &ueContextId, const UEContextRelease &uEContextRelease, Pistache::Http::ResponseWriter &response) {
    std::cout<<"ueContextId:"<<ueContextId<<"\nUEContextRelease:"<<uEContextRelease.toJson()<<std::endl;
    response.send(Pistache::Http::Code::Ok, "ReleaseUeContext\n");
}

}
}
}
}

