/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AccuracyFulfilmentIndicator.h
 *
 * 
 */

#ifndef AccuracyFulfilmentIndicator_H_
#define AccuracyFulfilmentIndicator_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AccuracyFulfilmentIndicator
    : public ModelBase
{
public:
    AccuracyFulfilmentIndicator();
    virtual ~AccuracyFulfilmentIndicator();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AccuracyFulfilmentIndicator members


protected:
};

}
}
}
}

#endif /* AccuracyFulfilmentIndicator_H_ */
