/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Ecgi.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Ecgi::Ecgi()
{
    m_EutraCellId = "";
    
}

Ecgi::~Ecgi()
{
}

void Ecgi::validate()
{
    // TODO: implement validation
}

nlohmann::json Ecgi::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["plmnId"] = ModelBase::toJson(m_PlmnId);
    val["eutraCellId"] = ModelBase::toJson(m_EutraCellId);
    

    return val;
}

void Ecgi::fromJson(const nlohmann::json& val)
{
    setEutraCellId(val.at("eutraCellId"));
    
}


PlmnId Ecgi::getPlmnId() const
{
    return m_PlmnId;
}
void Ecgi::setPlmnId(PlmnId const& value)
{
    m_PlmnId = value;
    
}
std::string Ecgi::getEutraCellId() const
{
    return m_EutraCellId;
}
void Ecgi::setEutraCellId(std::string const& value)
{
    m_EutraCellId = value;
    
}

}
}
}
}

