/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * GADShape.h
 *
 * 
 */

#ifndef GADShape_H_
#define GADShape_H_


#include "ModelBase.h"

#include "SupportedGADShapes.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  GADShape
    : public ModelBase
{
public:
    GADShape();
    virtual ~GADShape();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// GADShape members

    /// <summary>
    /// 
    /// </summary>
    SupportedGADShapes getShape() const;
    void setShape(SupportedGADShapes const& value);
    
protected:
    SupportedGADShapes m_Shape;

};

}
}
}
}

#endif /* GADShape_H_ */
