/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * GeographicArea.h
 *
 * 
 */

#ifndef GeographicArea_H_
#define GeographicArea_H_


#include "ModelBase.h"

#include "PointUncertaintyCircle.h"
#include "Point.h"
#include "PointUncertaintyEllipse.h"
#include "GeographicalCoordinates.h"
#include "PointAltitude.h"
#include "UncertaintyEllipse.h"
#include "EllipsoidArc.h"
#include "PointAltitudeUncertainty.h"
#include "Polygon.h"
#include <vector>
#include "SupportedGADShapes.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  GeographicArea
    : public ModelBase
{
public:
    GeographicArea();
    virtual ~GeographicArea();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// GeographicArea members

    /// <summary>
    /// 
    /// </summary>
    SupportedGADShapes getShape() const;
    void setShape(SupportedGADShapes const& value);
        /// <summary>
    /// 
    /// </summary>
    GeographicalCoordinates getPoint() const;
    void setPoint(GeographicalCoordinates const& value);
        /// <summary>
    /// 
    /// </summary>
    float getUncertainty() const;
    void setUncertainty(float const value);
        /// <summary>
    /// 
    /// </summary>
    UncertaintyEllipse getUncertaintyEllipse() const;
    void setUncertaintyEllipse(UncertaintyEllipse const& value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getConfidence() const;
    void setConfidence(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<GeographicalCoordinates>& getPointList();
        /// <summary>
    /// 
    /// </summary>
    float getAltitude() const;
    void setAltitude(float const value);
        /// <summary>
    /// 
    /// </summary>
    float getUncertaintyAltitude() const;
    void setUncertaintyAltitude(float const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getInnerRadius() const;
    void setInnerRadius(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    float getUncertaintyRadius() const;
    void setUncertaintyRadius(float const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getOffsetAngle() const;
    void setOffsetAngle(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getIncludedAngle() const;
    void setIncludedAngle(int32_t const value);
    
protected:
    SupportedGADShapes m_Shape;

    GeographicalCoordinates m_Point;

    float m_Uncertainty;

    UncertaintyEllipse m_UncertaintyEllipse;

    int32_t m_Confidence;

    std::vector<GeographicalCoordinates> m_PointList;

    float m_Altitude;

    float m_UncertaintyAltitude;

    int32_t m_InnerRadius;

    float m_UncertaintyRadius;

    int32_t m_OffsetAngle;

    int32_t m_IncludedAngle;

};

}
}
}
}

#endif /* GeographicArea_H_ */
