/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "HorizontalWithVerticalVelocityAndUncertainty.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

HorizontalWithVerticalVelocityAndUncertainty::HorizontalWithVerticalVelocityAndUncertainty()
{
    m_HSpeed = 0.0f;
    m_Bearing = 0;
    m_VSpeed = 0.0f;
    m_HUncertainty = 0.0f;
    m_VUncertainty = 0.0f;
    
}

HorizontalWithVerticalVelocityAndUncertainty::~HorizontalWithVerticalVelocityAndUncertainty()
{
}

void HorizontalWithVerticalVelocityAndUncertainty::validate()
{
    // TODO: implement validation
}

nlohmann::json HorizontalWithVerticalVelocityAndUncertainty::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["hSpeed"] = m_HSpeed;
    val["bearing"] = m_Bearing;
    val["vSpeed"] = m_VSpeed;
    val["vDirection"] = ModelBase::toJson(m_VDirection);
    val["hUncertainty"] = m_HUncertainty;
    val["vUncertainty"] = m_VUncertainty;
    

    return val;
}

void HorizontalWithVerticalVelocityAndUncertainty::fromJson(const nlohmann::json& val)
{
    setHSpeed(val.at("hSpeed"));
    setBearing(val.at("bearing"));
    setVSpeed(val.at("vSpeed"));
    setHUncertainty(val.at("hUncertainty"));
    setVUncertainty(val.at("vUncertainty"));
    
}


float HorizontalWithVerticalVelocityAndUncertainty::getHSpeed() const
{
    return m_HSpeed;
}
void HorizontalWithVerticalVelocityAndUncertainty::setHSpeed(float const value)
{
    m_HSpeed = value;
    
}
int32_t HorizontalWithVerticalVelocityAndUncertainty::getBearing() const
{
    return m_Bearing;
}
void HorizontalWithVerticalVelocityAndUncertainty::setBearing(int32_t const value)
{
    m_Bearing = value;
    
}
float HorizontalWithVerticalVelocityAndUncertainty::getVSpeed() const
{
    return m_VSpeed;
}
void HorizontalWithVerticalVelocityAndUncertainty::setVSpeed(float const value)
{
    m_VSpeed = value;
    
}
VerticalDirection HorizontalWithVerticalVelocityAndUncertainty::getVDirection() const
{
    return m_VDirection;
}
void HorizontalWithVerticalVelocityAndUncertainty::setVDirection(VerticalDirection const& value)
{
    m_VDirection = value;
    
}
float HorizontalWithVerticalVelocityAndUncertainty::getHUncertainty() const
{
    return m_HUncertainty;
}
void HorizontalWithVerticalVelocityAndUncertainty::setHUncertainty(float const value)
{
    m_HUncertainty = value;
    
}
float HorizontalWithVerticalVelocityAndUncertainty::getVUncertainty() const
{
    return m_VUncertainty;
}
void HorizontalWithVerticalVelocityAndUncertainty::setVUncertainty(float const value)
{
    m_VUncertainty = value;
    
}

}
}
}
}

