/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "LcsPriority.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

LcsPriority::LcsPriority()
{
    
}

LcsPriority::~LcsPriority()
{
}

void LcsPriority::validate()
{
    // TODO: implement validation
}

nlohmann::json LcsPriority::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void LcsPriority::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}

