/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LocationQoS.h
 *
 * 
 */

#ifndef LocationQoS_H_
#define LocationQoS_H_


#include "ModelBase.h"

#include "ResponseTime.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  LocationQoS
    : public ModelBase
{
public:
    LocationQoS();
    virtual ~LocationQoS();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// LocationQoS members

    /// <summary>
    /// 
    /// </summary>
    float getHAccuracy() const;
    void setHAccuracy(float const value);
    bool hAccuracyIsSet() const;
    void unsetHAccuracy();
    /// <summary>
    /// 
    /// </summary>
    float getVAccuracy() const;
    void setVAccuracy(float const value);
    bool vAccuracyIsSet() const;
    void unsetVAccuracy();
    /// <summary>
    /// 
    /// </summary>
    bool isVerticalRequested() const;
    void setVerticalRequested(bool const value);
    bool verticalRequestedIsSet() const;
    void unsetVerticalRequested();
    /// <summary>
    /// 
    /// </summary>
    ResponseTime getResponseTime() const;
    void setResponseTime(ResponseTime const& value);
    bool responseTimeIsSet() const;
    void unsetResponseTime();

protected:
    float m_HAccuracy;
    bool m_HAccuracyIsSet;
    float m_VAccuracy;
    bool m_VAccuracyIsSet;
    bool m_VerticalRequested;
    bool m_VerticalRequestedIsSet;
    ResponseTime m_ResponseTime;
    bool m_ResponseTimeIsSet;
};

}
}
}
}

#endif /* LocationQoS_H_ */
