/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Point.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Point::Point()
{
    
}

Point::~Point()
{
}

void Point::validate()
{
    // TODO: implement validation
}

nlohmann::json Point::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["shape"] = ModelBase::toJson(m_Shape);
    val["point"] = ModelBase::toJson(m_Point);
    

    return val;
}

void Point::fromJson(const nlohmann::json& val)
{
    
}


SupportedGADShapes Point::getShape() const
{
    return m_Shape;
}
void Point::setShape(SupportedGADShapes const& value)
{
    m_Shape = value;
    
}
GeographicalCoordinates Point::getPoint() const
{
    return m_Point;
}
void Point::setPoint(GeographicalCoordinates const& value)
{
    m_Point = value;
    
}

}
}
}
}

