/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PointAltitude.h
 *
 * 
 */

#ifndef PointAltitude_H_
#define PointAltitude_H_


#include "ModelBase.h"

#include "GeographicalCoordinates.h"
#include "GADShape.h"
#include "SupportedGADShapes.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  PointAltitude
    : public ModelBase
{
public:
    PointAltitude();
    virtual ~PointAltitude();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// PointAltitude members

    /// <summary>
    /// 
    /// </summary>
    SupportedGADShapes getShape() const;
    void setShape(SupportedGADShapes const& value);
        /// <summary>
    /// 
    /// </summary>
    GeographicalCoordinates getPoint() const;
    void setPoint(GeographicalCoordinates const& value);
        /// <summary>
    /// 
    /// </summary>
    float getAltitude() const;
    void setAltitude(float const value);
    
protected:
    SupportedGADShapes m_Shape;

    GeographicalCoordinates m_Point;

    float m_Altitude;

};

}
}
}
}

#endif /* PointAltitude_H_ */
