/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Polygon.h
 *
 * 
 */

#ifndef Polygon_H_
#define Polygon_H_


#include "ModelBase.h"

#include "GeographicalCoordinates.h"
#include "GADShape.h"
#include <vector>
#include "SupportedGADShapes.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Polygon
    : public ModelBase
{
public:
    Polygon();
    virtual ~Polygon();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Polygon members

    /// <summary>
    /// 
    /// </summary>
    SupportedGADShapes getShape() const;
    void setShape(SupportedGADShapes const& value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<GeographicalCoordinates>& getPointList();
    
protected:
    SupportedGADShapes m_Shape;

    std::vector<GeographicalCoordinates> m_PointList;

};

}
}
}
}

#endif /* Polygon_H_ */
