/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PositioningMethodAndUsage.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PositioningMethodAndUsage::PositioningMethodAndUsage()
{
    
}

PositioningMethodAndUsage::~PositioningMethodAndUsage()
{
}

void PositioningMethodAndUsage::validate()
{
    // TODO: implement validation
}

nlohmann::json PositioningMethodAndUsage::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["method"] = ModelBase::toJson(m_Method);
    val["mode"] = ModelBase::toJson(m_Mode);
    val["usage"] = ModelBase::toJson(m_Usage);
    

    return val;
}

void PositioningMethodAndUsage::fromJson(const nlohmann::json& val)
{
    
}


PositioningMethod PositioningMethodAndUsage::getMethod() const
{
    return m_Method;
}
void PositioningMethodAndUsage::setMethod(PositioningMethod const& value)
{
    m_Method = value;
    
}
PositioningMode PositioningMethodAndUsage::getMode() const
{
    return m_Mode;
}
void PositioningMethodAndUsage::setMode(PositioningMode const& value)
{
    m_Mode = value;
    
}
Usage PositioningMethodAndUsage::getUsage() const
{
    return m_Usage;
}
void PositioningMethodAndUsage::setUsage(Usage const& value)
{
    m_Usage = value;
    
}

}
}
}
}

