/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * VelocityEstimate.h
 *
 * 
 */

#ifndef VelocityEstimate_H_
#define VelocityEstimate_H_


#include "ModelBase.h"

#include "HorizontalVelocityWithUncertainty.h"
#include "HorizontalWithVerticalVelocityAndUncertainty.h"
#include "HorizontalWithVerticalVelocity.h"
#include "VerticalDirection.h"
#include "HorizontalVelocity.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  VelocityEstimate
    : public ModelBase
{
public:
    VelocityEstimate();
    virtual ~VelocityEstimate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// VelocityEstimate members

    /// <summary>
    /// 
    /// </summary>
    float getHSpeed() const;
    void setHSpeed(float const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getBearing() const;
    void setBearing(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    float getVSpeed() const;
    void setVSpeed(float const value);
        /// <summary>
    /// 
    /// </summary>
    VerticalDirection getVDirection() const;
    void setVDirection(VerticalDirection const& value);
        /// <summary>
    /// 
    /// </summary>
    float getHUncertainty() const;
    void setHUncertainty(float const value);
        /// <summary>
    /// 
    /// </summary>
    float getVUncertainty() const;
    void setVUncertainty(float const value);
    
protected:
    float m_HSpeed;

    int32_t m_Bearing;

    float m_VSpeed;

    VerticalDirection m_VDirection;

    float m_HUncertainty;

    float m_VUncertainty;

};

}
}
}
}

#endif /* VelocityEstimate_H_ */
