/**
* AMF MT Service
* AMF Mobile Termination Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EnableUeReachabilityReqData.h
 *
 * 
 */

#ifndef EnableUeReachabilityReqData_H_
#define EnableUeReachabilityReqData_H_


#include "ModelBase.h"

#include "UeReachability.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  EnableUeReachabilityReqData
    : public ModelBase
{
public:
    EnableUeReachabilityReqData();
    virtual ~EnableUeReachabilityReqData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// EnableUeReachabilityReqData members

    /// <summary>
    /// 
    /// </summary>
    UeReachability getReachability() const;
    void setReachability(UeReachability const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();

protected:
    UeReachability m_Reachability;

    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
};

}
}
}
}

#endif /* EnableUeReachabilityReqData_H_ */
