/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfStatusInfo.h
 *
 * 
 */

#ifndef AmfStatusInfo_H_
#define AmfStatusInfo_H_


#include "ModelBase.h"

#include "StatusChange.h"
#include "Guami.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AmfStatusInfo
    : public ModelBase
{
public:
    AmfStatusInfo();
    virtual ~AmfStatusInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AmfStatusInfo members

    /// <summary>
    /// 
    /// </summary>
    Guami getGuamis() const;
    void setGuamis(Guami const& value);
        /// <summary>
    /// 
    /// </summary>
    StatusChange getStatusChange() const;
    void setStatusChange(StatusChange const& value);
    
protected:
    Guami m_Guamis;

    StatusChange m_StatusChange;

};

}
}
}
}

#endif /* AmfStatusInfo_H_ */
