/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Arp.h
 *
 * 
 */

#ifndef Arp_H_
#define Arp_H_


#include "ModelBase.h"

#include "PreemptionCapability.h"
#include "PreemptionVulnerability.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Arp
    : public ModelBase
{
public:
    Arp();
    virtual ~Arp();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Arp members

    /// <summary>
    /// 
    /// </summary>
    int32_t getPriorityLevel() const;
    void setPriorityLevel(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    PreemptionCapability getPreemptCap() const;
    void setPreemptCap(PreemptionCapability const& value);
        /// <summary>
    /// 
    /// </summary>
    PreemptionVulnerability getPreemptVuln() const;
    void setPreemptVuln(PreemptionVulnerability const& value);
    
protected:
    int32_t m_PriorityLevel;

    PreemptionCapability m_PreemptCap;

    PreemptionVulnerability m_PreemptVuln;

};

}
}
}
}

#endif /* Arp_H_ */
