/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AssignEbiError.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

AssignEbiError::AssignEbiError()
{
    
}

AssignEbiError::~AssignEbiError()
{
}

void AssignEbiError::validate()
{
    // TODO: implement validation
}

nlohmann::json AssignEbiError::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["error"] = ModelBase::toJson(m_Error);
    val["failureDetails"] = ModelBase::toJson(m_FailureDetails);
    

    return val;
}

void AssignEbiError::fromJson(const nlohmann::json& val)
{
    
}


ProblemDetails AssignEbiError::getError() const
{
    return m_Error;
}
void AssignEbiError::setError(ProblemDetails const& value)
{
    m_Error = value;
    
}
AssignEbiFailed AssignEbiError::getFailureDetails() const
{
    return m_FailureDetails;
}
void AssignEbiError::setFailureDetails(AssignEbiFailed const& value)
{
    m_FailureDetails = value;
    
}

}
}
}
}

