/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AssignedEbi.h
 *
 * 
 */

#ifndef AssignedEbi_H_
#define AssignedEbi_H_


#include "ModelBase.h"
#include "EpsBearerId.h"
#include "EbiArpMapping.h"
#include <vector>
#include "Arp.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AssignedEbi
    : public ModelBase
{
public:
    AssignedEbi();
    virtual ~AssignedEbi();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AssignedEbi members

    /// <summary>
    /// 
    /// </summary>
    int32_t getPduSessionId() const;
    void setPduSessionId(int32_t const value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<EbiArpMapping>& getAssignedEbis();
        /// <summary>
    /// 
    /// </summary>
    std::vector<Arp>& getFailedArpList();
    bool failedArpListIsSet() const;
    void unsetFailedArpList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<EpsBearerId>& getReleasedEbiList();
    bool releasedEbiListIsSet() const;
    void unsetReleasedEbiList();

protected:
    int32_t m_PduSessionId;

    std::vector<EbiArpMapping> m_AssignedEbis;

    std::vector<Arp> m_FailedArpList;
    bool m_FailedArpListIsSet;
    std::vector<EpsBearerId> m_ReleasedEbiList;
    bool m_ReleasedEbiListIsSet;
};

}
}
}
}

#endif /* AssignedEbi_H_ */
