/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N2InformationNotification.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N2InformationNotification::N2InformationNotification()
{
    m_N2NotifySubscriptionId = "";
    
}

N2InformationNotification::~N2InformationNotification()
{
}

void N2InformationNotification::validate()
{
    // TODO: implement validation
}

nlohmann::json N2InformationNotification::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["n2NotifySubscriptionId"] = ModelBase::toJson(m_N2NotifySubscriptionId);
    val["n2InfoContainer"] = ModelBase::toJson(m_N2InfoContainer);
    

    return val;
}

void N2InformationNotification::fromJson(const nlohmann::json& val)
{
    setN2NotifySubscriptionId(val.at("n2NotifySubscriptionId"));
    
}


std::string N2InformationNotification::getN2NotifySubscriptionId() const
{
    return m_N2NotifySubscriptionId;
}
void N2InformationNotification::setN2NotifySubscriptionId(std::string const& value)
{
    m_N2NotifySubscriptionId = value;
    
}
N2InfoContainer N2InformationNotification::getN2InfoContainer() const
{
    return m_N2InfoContainer;
}
void N2InformationNotification::setN2InfoContainer(N2InfoContainer const& value)
{
    m_N2InfoContainer = value;
    
}

}
}
}
}

