/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NgRanTargetId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

NgRanTargetId::NgRanTargetId()
{
    m_RanNodeId = "";
    
}

NgRanTargetId::~NgRanTargetId()
{
}

void NgRanTargetId::validate()
{
    // TODO: implement validation
}

nlohmann::json NgRanTargetId::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["ranNodeId"] = ModelBase::toJson(m_RanNodeId);
    val["tai"] = ModelBase::toJson(m_Tai);
    

    return val;
}

void NgRanTargetId::fromJson(const nlohmann::json& val)
{
    setRanNodeId(val.at("ranNodeId"));
    
}


std::string NgRanTargetId::getRanNodeId() const
{
    return m_RanNodeId;
}
void NgRanTargetId::setRanNodeId(std::string const& value)
{
    m_RanNodeId = value;
    
}
Tai NgRanTargetId::getTai() const
{
    return m_Tai;
}
void NgRanTargetId::setTai(Tai const& value)
{
    m_Tai = value;
    
}

}
}
}
}

