/**
* AMF Location Service
* AMF Location Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * VerticalDirection.h
 *
 * 
 */

#ifndef VerticalDirection_H_
#define VerticalDirection_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  VerticalDirection
    : public ModelBase
{
public:
    VerticalDirection();
    virtual ~VerticalDirection();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// VerticalDirection members


protected:
};

}
}
}
}

#endif /* VerticalDirection_H_ */
