/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* AMFStatusChangeSubscribeModifyApiImpl.h
*
* 
*/

#ifndef AMF_STATUS_CHANGE_SUBSCRIBE_MODIFY_API_IMPL_H_
#define AMF_STATUS_CHANGE_SUBSCRIBE_MODIFY_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <AMFStatusChangeSubscribeModifyApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "SubscriptionData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class AMFStatusChangeSubscribeModifyApiImpl : public org::openapitools::server::api::AMFStatusChangeSubscribeModifyApi {
public:
    AMFStatusChangeSubscribeModifyApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~AMFStatusChangeSubscribeModifyApiImpl() {}

    void a_mf_status_change_subscribe_modfy(const std::string &subscriptionId, const SubscriptionData &subscriptionData, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif