/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "AMFStatusChangeSubscribeApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

AMFStatusChangeSubscribeApiImpl::AMFStatusChangeSubscribeApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : AMFStatusChangeSubscribeApi(rtr)
    { }

void AMFStatusChangeSubscribeApiImpl::a_mf_status_change_subscribe(const SubscriptionData &subscriptionData, Pistache::Http::ResponseWriter &response) {

    std::cout<<"AMFStatusChangeSubscribeApiImpl\n";
    std::cout<<subscriptionData.toJson()<<std::endl;
    response.send(Pistache::Http::Code::Ok, "Do some magic AMFStatusChangeSubscribeApiImpl.\n");
}

}
}
}
}

