/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* N1N2MessageTransferApiImpl.h
*
* 
*/

#ifndef N1_N2_MESSAGE_TRANSFER_API_IMPL_H_
#define N1_N2_MESSAGE_TRANSFER_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <N1N2MessageTransferApi.h>

#include <pistache/optional.h>

#include "N1N2MessageData.h"
#include "N1N2MessageTransferError.h"
#include "N1N2MessageTransferRspData.h"
#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class N1N2MessageTransferApiImpl : public org::openapitools::server::api::N1N2MessageTransferApi {
public:
    N1N2MessageTransferApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~N1N2MessageTransferApiImpl() {}

    void n1_n2_message_transfer(const std::string &ueContextId, const N1N2MessageData &n1N2MessageData, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif