/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "N1N2MessageUnSubscribeApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {



N1N2MessageUnSubscribeApiImpl::N1N2MessageUnSubscribeApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : N1N2MessageUnSubscribeApi(rtr)
    { }

void N1N2MessageUnSubscribeApiImpl::n1_n2_message_un_subscribe(const std::string &subscriptionId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

