/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* NonUEN2InfoSubscribeApiImpl.h
*
* 
*/

#ifndef NON_UEN2_INFO_SUBSCRIBE_API_IMPL_H_
#define NON_UEN2_INFO_SUBSCRIBE_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <NonUEN2InfoSubscribeApi.h>

#include <pistache/optional.h>

#include "NonUeN2InfoSubscriptionCreateData.h"
#include "NonUeN2InfoSubscriptionCreatedData.h"
#include "ProblemDetails.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class NonUEN2InfoSubscribeApiImpl : public org::openapitools::server::api::NonUEN2InfoSubscribeApi {
public:
    NonUEN2InfoSubscribeApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~NonUEN2InfoSubscribeApiImpl() {}

    void non_ue_n2_info_subscribe(const NonUeN2InfoSubscriptionCreateData &nonUeN2InfoSubscriptionCreateData, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif