/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* UEContextTransferApiImpl.h
*
* 
*/

#ifndef UE_CONTEXT_TRANSFER_API_IMPL_H_
#define UE_CONTEXT_TRANSFER_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <UEContextTransferApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "UeContextTransferReqData.h"
#include "UeContextTransferRspData.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class UEContextTransferApiImpl : public org::openapitools::server::api::UEContextTransferApi {
public:
    UEContextTransferApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~UEContextTransferApiImpl() {}

    void u_e_context_transfer(const std::string &ueContextId, const UeContextTransferReqData &ueContextTransferReqData, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif