/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfEventMode.h
 *
 * 
 */

#ifndef AmfEventMode_H_
#define AmfEventMode_H_


#include "ModelBase.h"

#include "AmfEventTrigger.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AmfEventMode
    : public ModelBase
{
public:
    AmfEventMode();
    virtual ~AmfEventMode();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AmfEventMode members

    /// <summary>
    /// 
    /// </summary>
    AmfEventTrigger getTrigger() const;
    void setTrigger(AmfEventTrigger const& value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getMaxReports() const;
    void setMaxReports(int32_t const value);
    bool maxReportsIsSet() const;
    void unsetMaxReports();
    /// <summary>
    /// 
    /// </summary>
    int32_t getDuration() const;
    void setDuration(int32_t const value);
    bool durationIsSet() const;
    void unsetDuration();

protected:
    AmfEventTrigger m_Trigger;

    int32_t m_MaxReports;
    bool m_MaxReportsIsSet;
    int32_t m_Duration;
    bool m_DurationIsSet;
};

}
}
}
}

#endif /* AmfEventMode_H_ */
