/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfEventState.h
 *
 * 
 */

#ifndef AmfEventState_H_
#define AmfEventState_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  AmfEventState
    : public ModelBase
{
public:
    AmfEventState();
    virtual ~AmfEventState();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// AmfEventState members

    /// <summary>
    /// 
    /// </summary>
    bool isActive() const;
    void setActive(bool const value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getRemainReports() const;
    void setRemainReports(int32_t const value);
    bool remainReportsIsSet() const;
    void unsetRemainReports();
    /// <summary>
    /// 
    /// </summary>
    int32_t getRemainDuration() const;
    void setRemainDuration(int32_t const value);
    bool remainDurationIsSet() const;
    void unsetRemainDuration();

protected:
    bool m_Active;

    int32_t m_RemainReports;
    bool m_RemainReportsIsSet;
    int32_t m_RemainDuration;
    bool m_RemainDurationIsSet;
};

}
}
}
}

#endif /* AmfEventState_H_ */
