/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EutraLocation.h
 *
 * 
 */

#ifndef EutraLocation_H_
#define EutraLocation_H_


#include "ModelBase.h"

#include "Ecgi.h"
#include "Tai.h"
#include <string>
#include "GlobalRanNodeId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  EutraLocation
    : public ModelBase
{
public:
    EutraLocation();
    virtual ~EutraLocation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// EutraLocation members

    /// <summary>
    /// 
    /// </summary>
    Tai getTai() const;
    void setTai(Tai const& value);
        /// <summary>
    /// 
    /// </summary>
    Ecgi getEcgi() const;
    void setEcgi(Ecgi const& value);
        /// <summary>
    /// 
    /// </summary>
    int32_t getAgeOfLocationInformation() const;
    void setAgeOfLocationInformation(int32_t const value);
    bool ageOfLocationInformationIsSet() const;
    void unsetAgeOfLocationInformation();
    /// <summary>
    /// 
    /// </summary>
    std::string getUeLocationTimestamp() const;
    void setUeLocationTimestamp(std::string const& value);
    bool ueLocationTimestampIsSet() const;
    void unsetUeLocationTimestamp();
    /// <summary>
    /// 
    /// </summary>
    std::string getGeographicalInformation() const;
    void setGeographicalInformation(std::string const& value);
    bool geographicalInformationIsSet() const;
    void unsetGeographicalInformation();
    /// <summary>
    /// 
    /// </summary>
    std::string getGeodeticInformation() const;
    void setGeodeticInformation(std::string const& value);
    bool geodeticInformationIsSet() const;
    void unsetGeodeticInformation();
    /// <summary>
    /// 
    /// </summary>
    GlobalRanNodeId getGlobalNgenbId() const;
    void setGlobalNgenbId(GlobalRanNodeId const& value);
    bool globalNgenbIdIsSet() const;
    void unsetGlobalNgenbId();

protected:
    Tai m_Tai;

    Ecgi m_Ecgi;

    int32_t m_AgeOfLocationInformation;
    bool m_AgeOfLocationInformationIsSet;
    std::string m_UeLocationTimestamp;
    bool m_UeLocationTimestampIsSet;
    std::string m_GeographicalInformation;
    bool m_GeographicalInformationIsSet;
    std::string m_GeodeticInformation;
    bool m_GeodeticInformationIsSet;
    GlobalRanNodeId m_GlobalNgenbId;
    bool m_GlobalNgenbIdIsSet;
};

}
}
}
}

#endif /* EutraLocation_H_ */
