/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PlmnId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

PlmnId::PlmnId()
{
    m_Mcc = "";
    m_Mnc = "";
    
}

PlmnId::~PlmnId()
{
}

void PlmnId::validate()
{
    // TODO: implement validation
}

nlohmann::json PlmnId::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["mcc"] = ModelBase::toJson(m_Mcc);
    val["mnc"] = ModelBase::toJson(m_Mnc);
    

    return val;
}

void PlmnId::fromJson(const nlohmann::json& val)
{
    setMcc(val.at("mcc"));
    setMnc(val.at("mnc"));
    
}


std::string PlmnId::getMcc() const
{
    return m_Mcc;
}
void PlmnId::setMcc(std::string const& value)
{
    m_Mcc = value;
    
}
std::string PlmnId::getMnc() const
{
    return m_Mnc;
}
void PlmnId::setMnc(std::string const& value)
{
    m_Mnc = value;
    
}

}
}
}
}

