/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscribedData.h
 *
 * 
 */

#ifndef SubscribedData_H_
#define SubscribedData_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  SubscribedData
    : public ModelBase
{
public:
    SubscribedData();
    virtual ~SubscribedData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// SubscribedData members

    /// <summary>
    /// 
    /// </summary>
    std::string getSari() const;
    void setSari(std::string const& value);
    bool sariIsSet() const;
    void unsetSari();
    /// <summary>
    /// 
    /// </summary>
    int32_t getRfspIndex() const;
    void setRfspIndex(int32_t const value);
    bool rfspIndexIsSet() const;
    void unsetRfspIndex();

protected:
    std::string m_Sari;
    bool m_SariIsSet;
    int32_t m_RfspIndex;
    bool m_RfspIndexIsSet;
};

}
}
}
}

#endif /* SubscribedData_H_ */
