/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UserLocation.h
 *
 * 
 */

#ifndef UserLocation_H_
#define UserLocation_H_


#include "ModelBase.h"

#include "EutraLocation.h"
#include "NrLocation.h"
#include "N3gaLocation.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  UserLocation
    : public ModelBase
{
public:
    UserLocation();
    virtual ~UserLocation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// UserLocation members

    /// <summary>
    /// 
    /// </summary>
    EutraLocation getEutraLocation() const;
    void setEutraLocation(EutraLocation const& value);
    bool eutraLocationIsSet() const;
    void unsetEutraLocation();
    /// <summary>
    /// 
    /// </summary>
    NrLocation getNrLocation() const;
    void setNrLocation(NrLocation const& value);
    bool nrLocationIsSet() const;
    void unsetNrLocation();
    /// <summary>
    /// 
    /// </summary>
    N3gaLocation getN3gaLocation() const;
    void setN3gaLocation(N3gaLocation const& value);
    bool n3gaLocationIsSet() const;
    void unsetN3gaLocation();

protected:
    EutraLocation m_EutraLocation;
    bool m_EutraLocationIsSet;
    NrLocation m_NrLocation;
    bool m_NrLocationIsSet;
    N3gaLocation m_N3gaLocation;
    bool m_N3gaLocationIsSet;
};

}
}
}
}

#endif /* UserLocation_H_ */
