/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Ecgi_2.h
 *
 * 
 */

#ifndef Ecgi_2_H_
#define Ecgi_2_H_


#include "ModelBase.h"

#include <string>
#include "PlmnId.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Ecgi_2
    : public ModelBase
{
public:
    Ecgi_2();
    virtual ~Ecgi_2();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Ecgi_2 members

    /// <summary>
    /// 
    /// </summary>
    PlmnId getPlmnId() const;
    void setPlmnId(PlmnId const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getEutraCellId() const;
    void setEutraCellId(std::string const& value);
    
protected:
    PlmnId m_PlmnId;

    std::string m_EutraCellId;

};

}
}
}
}

#endif /* Ecgi_2_H_ */
