/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N2InfoContent.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

N2InfoContent::N2InfoContent()
{
    m_NgapMessageType = 0;
    m_NgapMessageTypeIsSet = false;
    m_NgapIeType = 0;
    
}

N2InfoContent::~N2InfoContent()
{
}

void N2InfoContent::validate()
{
    // TODO: implement validation
}

nlohmann::json N2InfoContent::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_NgapMessageTypeIsSet)
    {
        val["ngapMessageType"] = m_NgapMessageType;
    }
    val["ngapIeType"] = m_NgapIeType;
    val["ngapData"] = ModelBase::toJson(m_NgapData);
    

    return val;
}

void N2InfoContent::fromJson(const nlohmann::json& val)
{
    if(val.find("ngapMessageType") != val.end())
    {
        setNgapMessageType(val.at("ngapMessageType"));
    }
    setNgapIeType(val.at("ngapIeType"));
    
}


int32_t N2InfoContent::getNgapMessageType() const
{
    return m_NgapMessageType;
}
void N2InfoContent::setNgapMessageType(int32_t const value)
{
    m_NgapMessageType = value;
    m_NgapMessageTypeIsSet = true;
}
bool N2InfoContent::ngapMessageTypeIsSet() const
{
    return m_NgapMessageTypeIsSet;
}
void N2InfoContent::unsetNgapMessageType()
{
    m_NgapMessageTypeIsSet = false;
}
int32_t N2InfoContent::getNgapIeType() const
{
    return m_NgapIeType;
}
void N2InfoContent::setNgapIeType(int32_t const value)
{
    m_NgapIeType = value;
    
}
RefToBinaryData N2InfoContent::getNgapData() const
{
    return m_NgapData;
}
void N2InfoContent::setNgapData(RefToBinaryData const& value)
{
    m_NgapData = value;
    
}

}
}
}
}

