/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SeafData.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

SeafData::SeafData()
{
    m_Nh = "";
    m_Ncc = 0;
    m_KeyAmfChangeInd = false;
    m_KeyAmfChangeIndIsSet = false;
    
}

SeafData::~SeafData()
{
}

void SeafData::validate()
{
    // TODO: implement validation
}

nlohmann::json SeafData::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["ngKsi"] = ModelBase::toJson(m_NgKsi);
    val["nh"] = ModelBase::toJson(m_Nh);
    val["ncc"] = m_Ncc;
    val["keyAmf"] = ModelBase::toJson(m_KeyAmf);
    if(m_KeyAmfChangeIndIsSet)
    {
        val["keyAmfChangeInd"] = m_KeyAmfChangeInd;
    }
    

    return val;
}

void SeafData::fromJson(const nlohmann::json& val)
{
    setNh(val.at("nh"));
    setNcc(val.at("ncc"));
    if(val.find("keyAmfChangeInd") != val.end())
    {
        setKeyAmfChangeInd(val.at("keyAmfChangeInd"));
    }
    
}


NgKsi SeafData::getNgKsi() const
{
    return m_NgKsi;
}
void SeafData::setNgKsi(NgKsi const& value)
{
    m_NgKsi = value;
    
}
std::string SeafData::getNh() const
{
    return m_Nh;
}
void SeafData::setNh(std::string const& value)
{
    m_Nh = value;
    
}
int32_t SeafData::getNcc() const
{
    return m_Ncc;
}
void SeafData::setNcc(int32_t const value)
{
    m_Ncc = value;
    
}
KeyAmf SeafData::getKeyAmf() const
{
    return m_KeyAmf;
}
void SeafData::setKeyAmf(KeyAmf const& value)
{
    m_KeyAmf = value;
    
}
bool SeafData::isKeyAmfChangeInd() const
{
    return m_KeyAmfChangeInd;
}
void SeafData::setKeyAmfChangeInd(bool const value)
{
    m_KeyAmfChangeInd = value;
    m_KeyAmfChangeIndIsSet = true;
}
bool SeafData::keyAmfChangeIndIsSet() const
{
    return m_KeyAmfChangeIndIsSet;
}
void SeafData::unsetKeyAmfChangeInd()
{
    m_KeyAmfChangeIndIsSet = false;
}

}
}
}
}

