/**
* AMF Communicaiton Service
* AMF Communication Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscriptionData.h
 *
 * 
 */

#ifndef SubscriptionData_H_
#define SubscriptionData_H_


#include "ModelBase.h"

#include <string>
#include "Guami.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  SubscriptionData
    : public ModelBase
{
public:
    SubscriptionData();
    virtual ~SubscriptionData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// SubscriptionData members

    /// <summary>
    /// 
    /// </summary>
    std::string getAmfStatusUri() const;
    void setAmfStatusUri(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    Guami getGuamis() const;
    void setGuamis(Guami const& value);
    bool guamisIsSet() const;
    void unsetGuamis();

protected:
    std::string m_AmfStatusUri;

    Guami m_Guamis;
    bool m_GuamisIsSet;
};

}
}
}
}

#endif /* SubscriptionData_H_ */
