/**
* Namf_EventExposure Service
* AMF Event Exposure Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* CreateSubscriptionApiImpl.h
*
* 
*/

#ifndef CREATE_SUBSCRIPTION_API_IMPL_H_
#define CREATE_SUBSCRIPTION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <CreateSubscriptionApi.h>

#include <pistache/optional.h>

#include "AmfCreateEventSubscription.h"
#include "AmfCreatedEventSubscription.h"
#include "ProblemDetails.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class CreateSubscriptionApiImpl : public org::openapitools::server::api::CreateSubscriptionApi {
public:
    CreateSubscriptionApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~CreateSubscriptionApiImpl() {}

    void create_subscription(const AmfCreateEventSubscription &amfCreateEventSubscription, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif