/**
* AMF MT Service
* AMF Mobile Termination Service
*
* OpenAPI spec version: 1.R15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "ProvideDomainSelectionInfoApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

ProvideDomainSelectionInfoApiImpl::ProvideDomainSelectionInfoApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr)
    : ProvideDomainSelectionInfoApi(rtr)
    { }

void ProvideDomainSelectionInfoApiImpl::provide_domain_selection_info(const std::string &ueContextId, const Pistache::Optional<UeContextInfoClass> &infoClass, const Pistache::Optional<std::string> &supportedFeatures, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

